name: auto-update-and-bump
on:
  push:
     branches:
       - main
  pull_request:
     types: [opened, labeled]
     branches:
       - main
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.TEST_GHA_TOKEN }}"
          PR_FILTER: "labelled"
          PR_LABELS: "autoupdate"
          MERGE_CONFLICT_ACTION: "ignore"
          MERGE_MSG: "Automatically kept this PR up to date with develop"
  autobump:
    needs: autoupdate
    name: autobump
    runs-on: ubuntu-18.04
    steps:
      - name: Auto Bump Check
        id: autobump-check
        uses: docker://francescoferraioli/autobump-action-unstable:v1
        env:
          GITHUB_TOKEN: "${{ secrets.TEST_GHA_TOKEN }}"
          PACKAGES_IN_REPO: "default|;domain|packages/domain;contracts|packages/contracts;bus-configuration|packages/bus-configuration"

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: "${{ secrets.TEST_GHA_TOKEN }}"

      - name: Auto Bump Run
        uses: francescoferraioli/autobump@v4.0.1
        with:
          AUTOBUMP_RUN: ${{ steps.autobump-check.outputs.AUTOBUMP_RUN }}
          AUTOBUMP_USER_NAME: "francescoferraioli"
          AUTOBUMP_USER_EMAIL: "francesco.ferraioli@outlook.com"