name: autobump
on:
  push:
     branches:
       - '*'
       - '!main'
jobs:
  autobump:
    name: autobump
    runs-on: ubuntu-18.04
    steps:
      - name: Auto Bump Action
        id: autobump-action
        uses: docker://francescoferraioli/autobump-action-unstable:v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PR_FILTER: "labelled"
          PR_LABELS: "autobump"
          MERGE_CONFLICT_ACTION: "ignore"
          MERGE_MSG: "Automatically bumped"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Script
        run: .github/run-script.sh
        env:
          FRANKIE_TEST: ${{ steps.autobump-action.outputs.FRANKIE_TEST }}
          ANOTHER_TEST: ${{ steps.autobump-action.outputs.ANOTHER_TEST }}