name: auto-update-and-bump
on:
  push:
     branches:
       - main
jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PR_FILTER: "labelled"
          PR_LABELS: "autoupdate"
          MERGE_CONFLICT_ACTION: "ignore"
          MERGE_MSG: "Automatically kept this PR up to date with develop"
  autobump:
    needs: autoupdate
    name: autobump
    runs-on: ubuntu-18.04
    steps:
      - name: Auto Bump Action
        id: autobump-action
        uses: docker://francescoferraioli/autobump-action-unstable:v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          PACKAGES_TO_CHECK: "default|./"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Script
        run: .github/run-script.sh
        env:
          AUTOBUMP_RUN: ${{ steps.autobump-action.outputs.AUTOBUMP_RUN }}